version: '3'

services:
  web:
    image: php-nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - db
    # links:
    #   - php-fpm
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/default.conf:/etc/nginx/sites-enabled/default"
      - "./web:/var/www/myservice"
    ports:
      - 80:80

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: my_root_password
    volumes:
      - "./mysql_data:/var/lib/mysql"
      - "./mysqld_charset.cnf:/etc/my.cnf"
    ports:
      - "6033:3306"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      restart: always
    ports:
      - 8080:80

